### ISSUE TITLE
Move Weekends Problem

### ISSUE THREAD

**Issue by ankidoc** [vasarmilan/AnkiWeekendsAndHolidays#2]
Please help me! 

I tried your add on and did something wrong. How can I undo the changes made with your add on?? Even after a back up it still keeps the gaps but I decided, that I want it back the old way without a day of skipping. But now it seems there is no way back? How can I undo the changes? Please, I'm a med student before the exams, I need it to work! 

Greetings

**Comment by vasarmilan** [comment]
Hi,

Remove the add-on and restore a backup made before applying the add-on.
