### ISSUE TITLE
How to undo rescheduled cards?

### ISSUE THREAD

**Issue by Ankigithub07** [vasarmilan/AnkiWeekendsAndHolidays#3]
I was trying out your Move Reviews from Weekends and Holidays (works with already learnt and mobile) add-on, but I forgot to backup my scheduling progress. As I enabled this add-on, I accidently freed up the day which I want to study and now I want to reset my progress. Please help me. I want to undo rescheduling.

**Comment by vasarmilan** [comment]
Hi,
1) Anki makes automatic backups, if I remember correctly it should be daily. So if that works for you, you should be able to find them in the Anki data folder.
2) If you cannot find it, you can just try running a new rescheduling disabling the other days, not a perfect solution but it'll get some back to the day that you want to study on. And make sure to backup next time :)
