### ISSUE TITLE
Fork vs update of this add-on

### ISSUE THREAD

**Issue by AnKingMed** [vasarmilan/AnkiWeekendsAndHolidays#4]
I recently came across your add-on and was very impressed. I have been wanting to make a similar add-on that only moves mature cards around. I am considering paying someone to significantly improve this add-on in a lot of ways and wanted to get your blessing before doing so.  I could have them create a PR, but then it would require you to manage it, etc.  Would you be ok if I forked your add-on and make significant changes and released it as a separate add-on that I will maintain? I don't want to step on your toes so if you'd prefer not then perhaps we could find a different way to work together

Ideas I'm thinking of are: adding a better config UI, making it so it only moves cards with interval longer than x days, adding an option to only reschedule certain decks, adding an undo feature, etc etc

Feel free to email me at ankingmed@gmail.com if that's easier

**Comment by vasarmilan** [comment]
Hi @AnKingMed,

I'm happy to see you find my add-on useful! Feel free to fork it and release it as a new add-on.
