### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by aboali19** [vasarmilan/AnkiWeekendsAndHolidays#5]
this is the config for this Addon but this was not working at any time.  (Anki version is 2.1.48 )
{
    "dates": [
        "1970-01-01"
    ],
    "execute_at_startup": 0,
    "max_change_days": 7,
    "max_change_percent": 10,
    "max_days_lookahead": 365,
    "shortcut": "Ctrl+Shift+r",
    "weekdays_skip": [
        5,
        6
    ]
}

**Comment by vasarmilan** [comment]
Did you run the reschedule by pressing "Ctrl+Shift+r"?

**Comment by aboali19** [comment]
sorry, I did it many times And I did not find anything to work.

**Comment by vasarmilan** [comment]
@aboali1hassona 
I see. Unfortunately I do not have the time to support this add-on any more, but this fork is in active development: https://github.com/ankipalace/AnkiWeekendsAndHolidays

So you might have a better chance there.
